### ISSUE TITLE
Limitar tamanho do nome do usuário

### ISSUE THREAD

**Issue by carlosxis** [ottimizza/web-accounts#15]
Vide imagem. Cria barra de rolagem.
![login-prosperando](https://user-images.githubusercontent.com/54960151/71586851-508f9880-2afa-11ea-8564-1db6fa941c97.PNG)

**Comment by mtslucasmartins** [comment]
#### Correção
Adicionado overflow ellipsis no campo.

![image](https://user-images.githubusercontent.com/20546341/71591641-da942d00-2b0b-11ea-8a02-07e88f25b566.png)
