### ISSUE TITLE
Contabilidade sem logo perde 

### ISSUE THREAD

**Issue by carlosxis** [ottimizza/web-accounts#26]
**Descreva o Bug**
 Quando temos uma contabilidade sem logo (admin@futuro.com,br senha ottimizza)  - staging, a imagem que fica no logar da log é muito grande.

![image](https://user-images.githubusercontent.com/54960151/71601373-eeeb2080-2b31-11ea-918b-e3ef72ac32a3.png)

**Comment by mtslucasmartins** [comment]
Resolvido!
