### ISSUE TITLE
Link de redefinição de senha não abre tela

### ISSUE THREAD

**Issue by carlosxis** [ottimizza/web-accounts#28]
**Descreva o Bug**
 Quando clico em redefinir senha, recebo o email porém não abre tela para colocar senha nova.

**Como Reproduzir**
Entrar na opção de login e clicar em redefinir senha. Informar seu email xavier@ottimizza.com.br ou um válido.

PS: estava logado no Tareffa Oauth  com outro usuário.
Tentei Colar o link da redefinição no browser normal e no anônimo.
 
**Comportamento Esperado**
Receber Email
Clicar no Link
Conseguir alterar a senha.
 
**Link Xavier**
 
https://accounts.ottimizza.com.br/password_reset?username=xavier%40ottimizza.com.br&token=610f4774-8ada-417d-a808-f678521c086f

Este foi o link recebido onde não consegui alter a senha.

**Comment by carlosxis** [comment]
Testei como https://oauth.ottimizza.com.br/password_reset?username=xavier%40ottimizza.com.br&token=610f4774-8ada-417d-a808-f678521c086f  e funcionou.

**Comment by carlosxis** [comment]
Tem como ficar em variável de ambiente para trocarmos tareffa por Ottimizza ? o se colocar no corpo do email tareffa também funciona o oauth-tareffa que temos em paralelo ?

**Comment by mtslucasmartins** [comment]
Issue Corrigido
